version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              git clone git@github.com:salortiz/NativeHelpers-Blob.git /tmp/ncb && cd /tmp/ncb && zef install --force .
              zef install --force-test -v --deps-only .
      - run:
          name: test 
          command: |
              zef test .
